const TECH_STACKS = [
  ".NET",
  ".NET Core",
  ".NET MVC",
  "3D Graphics",
  "3P APIs & Libraries",
  "A/B Testing",
  "Acceptance Testing",
  "Access",
  "Administration",
  "ADO.NET",
  "Adobe Air",
  "Adobe Illustrator",
  "Adobe InDesign",
  "Adobe Photoshop",
  "Adobe XD",
  "AdonisJS",
  "AEM",
  "AES/RSA Encryption",
  "Agile",
  "Airflow",
  "AJAX",
  "Akka",
  "AL Programming",
  "Algorithms and Data Structures",
  "Alteryx",
  "Amazon Firehose",
  "Amazon Kinesis",
  "Amazon Redshift",
  "AMP (Accelerated Mobile Pages)",
  "Android",
  "Android - Java",
  "Android Hybrid App Development",
  "Android SDK",
  "Android Studio",
  "Android Testing",
  "Android/Java",
  "Android/Kotlin",
  "Angular",
  "Angular 2+",
  "Angular CLI",
  "AngularJS",
  "Ansible",
  "Ant Design",
  "Apache",
  "Apache Beam",
  "Apache Flume",
  "Apache Kafka",
  "Apache Mesos",
  "Apache NiFi",
  "Apache Pulsar",
  "Apache Solr",
  "Apache Spark",
  "Apache Storm",
  "Apex Programming",
  "API Design",
  "API Documentation",
  "API Integrations",
  "Apollo",
  "Apollo Client",
  "Apollo Server",
  "ArcGIS JavaScript API",
  "Arduino",
  "Arista",
  "Artificial Intelligence",
  "Artificial Neural Networks",
  "AS3",
  "ASP.NET",
  "ASP.NET Boilerplate",
  "ASP.NET Core",
  "ASP.NET MVC",
  "ASP.NET Web Forms",
  "ASP.NET/C#",
  "Assembly",
  "Atlassian",
  "Atom",
  "AutoIT",
  "Automatics",
  "Automation Test Toolkit",
  "Automation Testing",
  "AWS",
  "AWS Administration",
  "AWS Amplify",
  "AWS Aurora",
  "AWS Cognito",
  "AWS DevOps",
  "AWS Glue",
  "AWS Lambda",
  "AWS Solutions Architecture",
  "Axio",
  "Axure",
  "Azure",
  "Azure Cloud SQL",
  "Azure Cosmos DB",
  "Azure Data Factory",
  "Azure Data Lake",
  "Azure Databricks",
  "Azure DevOps",
  "Azure Eventhub",
  "Azure Function App",
  "Azure Modern Data",
  "Babel",
  "Back-End Development",
  "Backbone",
  "Bash",
  "Bayesian Models",
  "BDD/Behavior-Driven Development",
  "Benchmarks",
  "BI Admin",
  "BI Support",
  "Bias-Variance Tradeoff",
  "Big Data",
  "Bitbucket",
  "BizTalk Server",
  "Blender",
  "Blockchain",
  "BluePrint",
  "Bootstrap",
  "Borland Delphi",
  "Business Analysis",
  "Business Application Development",
  "Business Intelligence",
  "Business Intelligence Engineering",
  "C",
  "C#",
  "C++",
  "C/AL Development",
  "Caffe",
  "CakePHP",
  "CalDav/CardDav",
  "Cards & Payment",
  "Cassandra",
  "Chai",
  "Chatbot",
  "Chef",
  "Chrome Extensions",
  "CI/CD",
  "CircleCI",
  "Cisco",
  "Cisco Contact Centers",
  "Citrix",
  "Classic ASP",
  "Classic VB",
  "Clean Architecture",
  "Clojure",
  "ClojureScript",
  "Cloud",
  "Cloud Migration",
  "COBOL",
  "Cocos Creator",
  "Code Analysis",
  "Code Reviews",
  "CodeIgniter",
  "CoffeeScript",
  "Cognos",
  "ColdFusion",
  "Coldfusion CFML",
  "Communication",
  "Compass",
  "Computer Vision",
  "Confluence",
  "Consul",
  "CORBA",
  "Cordova",
  "Core Java",
  "CoreOS",
  "CouchDB",
  "Cplex",
  "Crawlers",
  "Critical Thinking",
  "Crystal Reports",
  "CSS",
  "CSS Modules",
  "CSS3",
  "CSS: Animation",
  "CSS: Flex",
  "CSS: Grid",
  "CSS: Media Queries",
  "Customer Interaction",
  "Cyber Security",
  "Cypress",
  "D3.js",
  "DAC",
  "Dagger",
  "Dart",
  "Data Analysis",
  "Data Analyst",
  "Data Cleansing",
  "Data Engineering",
  "Data Extraction",
  "Data Migration",
  "Data Modeling",
  "Data Pipelines",
  "Data Science",
  "Data Spooling",
  "Data Warehousing",
  "Database Administration",
  "DB2 Universal Database (UDB)",
  "Decision Trees",
  "Deep Learning",
  "Deep Learning Algorithms",
  "Delphi",
  "Design Patterns",
  "Design Thinking",
  "DevExpress",
  "DevOps",
  "Digital Marketing",
  "Disaster Recovery",
  "Discriminant Analysis",
  "Distributed File Systems",
  "Distributed Programming",
  "Distributed Storage",
  "Distributed Systems",
  "Django",
  "Django Rest Framework",
  "DNS",
  "Docker",
  "DOM",
  "Domain Driven Design",
  "Domain-Specific Languages",
  "Dplyr",
  "Drupal",
  "DuckDuckGo",
  "Durandal.js",
  "Dynamics 365 Business Central",
  "DynamoDB",
  "E-Commerce",
  "E2E Testing",
  "EC2",
  "EDA",
  "EJB Component Programming",
  "Elastic BeanStalk",
  "Elastic Beats (Filebeat, etc.)",
  "ElasticSearch",
  "Electrical Networks",
  "Electron",
  "Electronic Billing",
  "Electronic Engineering and Telecommunications",
  "Electronics",
  "Elixir",
  "ELK stack",
  "ELM",
  "Embedded Systems",
  "Ember.js",
  "EMV",
  "Ensemble Methods",
  "Entity Framework",
  "EO/IR",
  "Erlang",
  "ERP",
  "ERP Development",
  "Ethical Hacking",
  "ETL",
  "Excel",
  "Excel VBA",
  "Exchange ActiveSync",
  "Exploration/Exploitation",
  "Express.js",
  "ExtJS",
  "Facebook API",
  "Feathers JS",
  "FFmpeg",
  "Figma",
  "Filemaker Development",
  "Filemaker Go",
  "Filemaker Pro",
  "Filemaker WebDirect",
  "Finance",
  "Fire",
  "Firebase",
  "Firewalls",
  "Firmware",
  "Flash",
  "Flask",
  "Flutter",
  "Flux",
  "Free Form",
  "Fullstack Development",
  "Functional Testing",
  "Game Development",
  "Gatsby",
  "GCP",
  "Gerrit",
  "Ggplot2",
  "Git",
  "Gitflow",
  "GitHub",
  "GitLab",
  "Go/Golang",
  "Godot Engine",
  "Google Apps",
  "Google Cloud Platform",
  "Google Web Toolkit",
  "Gradle",
  "Grafana",
  "Graphene",
  "Graphic Design",
  "Graphite",
  "GraphQL",
  "Greenplum",
  "Groovy",
  "Groovy on Grails",
  "Growth Hacking",
  "GRPC",
  "GTK",
  "Guidewire",
  "GWT",
  "H2O",
  "Hadoop",
  "HAProxy",
  "Hardware Project",
  "Haskell",
  "HBase",
  "HDFS",
  "Helpdesk Analyst I/II",
  "Heroku",
  "Hibernate",
  "Highcharts",
  "HL7 Messages",
  "HRM",
  "HTML",
  "HTML Preprocessors",
  "HTML5",
  "HTTP",
  "Human Resources & Talent",
  "Hybrid Cloud Management",
  "Hyperledger Fabric",
  "IBM DataPower",
  "IBM ESB",
  "IBM Watson",
  "IBM WPS",
  "ICMP",
  "iMacros",
  "Image Recognition",
  "IMAP",
  "IMS/IP Multimedia Subsystem",
  "Individual Contributor",
  "Informatica",
  "Information Technology",
  "Infrastructure Operations",
  "Innosetup",
  "Instance-Based and Association Learning",
  "Integration Testing",
  "Internal Audit",
  "Inventory",
  "Invision",
  "Ionic",
  "iOS - Swift",
  "iOS Development",
  "IoT",
  "IPFS",
  "IPMI",
  "iSCSI / CIFS",
  "IT Officer",
  "Iterative Testing",
  "ITSM",
  "J2EE",
  "Jamf",
  "Jasper Reports",
  "Java",
  "Java 8",
  "Java JSF",
  "JavaScript",
  "Javascript ES6",
  "JavaScript Frameworks",
  "JDBC",
  "JEE",
  "Jekyll",
  "Jenkins", 
];

export default TECH_STACKS